# Generated by Django 4.0.2 on 2022-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=10)),
                ('color', models.IntegerField(default=6908265)),
                ('scan', models.BooleanField(default=False)),
            ],
        ),
    ]
